// src/scripts/seedCustomers.js
// Run: node src/scripts/seedCustomers.js
//
// Seeds 4 customers that form a real referral chain:
//   Pavithra (founder / no referrer)
//   └── Priya  (referred by Pavithra)
//       └── Divya  (referred by Priya)
//   Ananya (typed an invalid code — still saved, referralValid = false)
//
// WHY a script: lets you verify schema + code generation without a live UI.

require('dotenv').config();
const mongoose = require('mongoose');
const Customer = require('../models/Customer');

// ── helper: wait a tick so Mongo uses the unique index before next insert ──
const delay = ms => new Promise(r => setTimeout(r, ms));

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('✅ Connected to MongoDB\n');

  // ── Wipe existing seed data (phone numbers used here only) ───────────────
  await Customer.deleteMany({
    phone: { $in: ['9000000001', '9000000002', '9000000003', '9000000004'] }
  });
  console.log('🗑  Cleared previous seed customers\n');

  // ── Customer 1: Pavithra — the original founder / first customer ─────────
  // No referral code; myReferralCode is auto-generated by schema default.
  const pavithra = await Customer.create({
    name:  'Pavithra R',
    phone: '9000000001',
    email: 'pavithra@example.com',
    // referredBy:        null  (default)
    // referralValid:     false (default)
    // referredByCustomer: null (default)
  });
  console.log('👤 Customer 1 — Pavithra (no referrer)');
  console.log(JSON.stringify(pavithra.toObject(), null, 2));
  console.log('\n' + '─'.repeat(60) + '\n');
  await delay(50);

  // ── Customer 2: Priya — referred by Pavithra's code ─────────────────────
  const pavithraCode = pavithra.myReferralCode; // e.g. "YC-K7MR"
  const referrer2    = await Customer.findOne({ myReferralCode: pavithraCode });

  const priya = await Customer.create({
    name:               'Priya Sharma',
    phone:              '9000000002',
    email:              'priya@example.com',
    referredBy:         pavithraCode,
    referralValid:      !!referrer2,
    referredByCustomer: referrer2?._id ?? null,
  });
  console.log(`👤 Customer 2 — Priya (referred by Pavithra using ${pavithraCode})`);
  console.log(JSON.stringify(priya.toObject(), null, 2));
  console.log('\n' + '─'.repeat(60) + '\n');
  await delay(50);

  // ── Customer 3: Divya — referred by Priya's code ────────────────────────
  const priyaCode = priya.myReferralCode;
  const referrer3 = await Customer.findOne({ myReferralCode: priyaCode });

  const divya = await Customer.create({
    name:               'Divya Nair',
    phone:              '9000000003',
    email:              'divya@example.com',
    referredBy:         priyaCode,
    referralValid:      !!referrer3,
    referredByCustomer: referrer3?._id ?? null,
  });
  console.log(`👤 Customer 3 — Divya (referred by Priya using ${priyaCode})`);
  console.log(JSON.stringify(divya.toObject(), null, 2));
  console.log('\n' + '─'.repeat(60) + '\n');
  await delay(50);

  // ── Customer 4: Ananya — typed a wrong code ──────────────────────────────
  const fakeCode  = 'YC-FAKE';
  const referrer4 = await Customer.findOne({ myReferralCode: fakeCode }); // null

  const ananya = await Customer.create({
    name:               'Ananya Menon',
    phone:              '9000000004',
    email:              'ananya@example.com',
    referredBy:         fakeCode,
    referralValid:      !!referrer4,   // false — code not found
    referredByCustomer: referrer4?._id ?? null,
  });
  console.log(`👤 Customer 4 — Ananya (invalid code ${fakeCode} — still saved)`);
  console.log(JSON.stringify(ananya.toObject(), null, 2));
  console.log('\n' + '─'.repeat(60) + '\n');

  // ── Summary queries ───────────────────────────────────────────────────────
  const validReferrals = await Customer.find({ referralValid: true }).select('name referredBy referralValid');
  console.log('📊 All customers with referralValid = true:');
  console.log(JSON.stringify(validReferrals, null, 2));

  const byPavithra = await Customer.find({ referredByCustomer: pavithra._id }).select('name phone referredBy');
  console.log(`\n📊 Customers referred directly by Pavithra (${pavithra.myReferralCode}):`);
  console.log(JSON.stringify(byPavithra, null, 2));

  await mongoose.disconnect();
  console.log('\n✅ Seed complete. Disconnected from MongoDB.');
}

seed().catch(err => {
  console.error('❌ Seed failed:', err.message);
  process.exit(1);
});
